const actionTypes = {
    GET_AUTH_TOKEN: "GET_AUTH_TOKEN",
    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',

    GET_MOVIE_LIST: 'GET_MOVIE_LIST',
    MOVIE_LIST_SUCCESS: 'MOVIE_LIST_SUCCESS',
    MOVIE_LIST_FAILURE: 'MOVIE_LIST_FAILURE',
    
    FETCH_AIR_NOW_LIST: 'FETCH_AIR_NOW_LIST',
    FETCH_AIR_NOW_SUCCESS: 'FETCH_AIR_NOW_SUCCESS',
    FETCH_AIR_NOW_FAILURE: 'FETCH_AIR_NOW_FAILURE',

    GET_MOVIE_DETAILS: 'GET_MOVIE_DETAILS',
    MOVIE_DETAILS_SUCCESS: 'MOVIE_DETAILS_SUCCESS',
    MOVIE_DETAILS_FAILURE: 'MOVIE_DETAILS_FAILURE',

}
export default actionTypes;